apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: my-container
        image: us-central1-docker.pkg.dev/plucky-balm-450118-b9/my-repo/my-app:blue
        ports:
        - containerPort: 80