name: Docker Build & Push

on:
  push:
    branches: [ main ]  # Change this to your default branch
    paths:
      - "Dockerfile"     # Runs only when the Dockerfile changes

  workflow_dispatch:      # Allows manual execution

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login to Docker Hub using GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cloud:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cloud:latest

